package clusterdoctor

import (
	"context"
	"time"

	"github.com/google/uuid"
	"k8s.io/client-go/kubernetes"
)

// ScanStatus mirrors the `status` column of the scans table.
type ScanStatus string

const (
	ScanRunning   ScanStatus = "running"
	ScanCompleted ScanStatus = "completed"
	ScanFailed    ScanStatus = "failed"
	ScanPartial   ScanStatus = "partial"
)

// ScanProgressEvent is one line of the SSE stream at
// /cluster-doctor/scan/:id/status.
type ScanProgressEvent struct {
	Type     string   `json:"type"` // category_started | category_completed | finding | scan_completed | scan_failed
	Category string   `json:"category,omitempty"`
	Finding  *Finding `json:"finding,omitempty"`
	Error    string   `json:"error,omitempty"`
}

// ScanResult is the outcome of one Scanner.Run call.
type ScanResult struct {
	ID            string
	Cluster       string
	StartedAt     time.Time
	CompletedAt   time.Time
	Status        ScanStatus
	Findings      []Finding
	SkippedChecks int
	ErrorMessage  string
}

// Scanner runs a fixed rule set against a cluster.
type Scanner struct {
	Rules []Rule
}

// NewScanner builds a Scanner from an already-loaded rule set.
func NewScanner(rules []Rule) *Scanner {
	return &Scanner{Rules: rules}
}

// Run executes every enabled rule, grouped by category, against clientset.
// scanID is generated by the caller (e.g. the HTTP handler, so it can
// respond with the id before the scan finishes) rather than by Run itself.
// A check with no registered implementation, or one that errors (commonly a
// 403 from insufficient RBAC), is counted in SkippedChecks rather than
// aborting the scan — per the "graceful degradation" requirement, one bad
// check must never take down the whole report. If progress is non-nil,
// per-category and per-finding events are sent to it as they happen; Run
// closes progress before returning.
func (s *Scanner) Run(
	ctx context.Context,
	clientset kubernetes.Interface,
	cluster string,
	scanID string,
	progress chan<- ScanProgressEvent,
) *ScanResult {
	if progress != nil {
		defer close(progress)
	}

	result := &ScanResult{
		ID:        scanID,
		Cluster:   cluster,
		StartedAt: time.Now().UTC(),
		Status:    ScanRunning,
	}

	for _, category := range s.categories() {
		emit(ctx, progress, ScanProgressEvent{Type: "category_started", Category: category})

		for _, rule := range s.Rules {
			if !rule.Enabled || rule.Category != category {
				continue
			}

			if ctx.Err() != nil {
				result.Status = ScanPartial
				result.ErrorMessage = "scan timed out or was cancelled"

				break
			}

			fn, ok := GetCheck(rule.CheckFn)
			if !ok {
				result.SkippedChecks++
				continue
			}

			raws, err := fn(ctx, clientset)
			if err != nil {
				result.SkippedChecks++
				continue
			}

			for _, raw := range raws {
				finding := Finding{
					ID:                 uuid.NewString(),
					ScanID:             result.ID,
					RuleID:             rule.ID,
					RuleName:           rule.Name,
					Severity:           rule.Severity,
					Category:           rule.Category,
					Namespace:          raw.Namespace,
					ResourceKind:       raw.ResourceKind,
					ResourceName:       raw.ResourceName,
					Description:        rule.Description,
					Remediation:        rule.Remediation,
					References:         rule.References,
					RawObject:          raw.RawObject,
					DetectedAt:         time.Now().UTC(),
					GuidedFixAvailable: rule.GuidedFix.Action != "",
					GuidedFixAction:    rule.GuidedFix.Action,
					GuidedFixWarning:   rule.GuidedFix.Warning,
				}
				result.Findings = append(result.Findings, finding)
				emit(ctx, progress, ScanProgressEvent{Type: "finding", Finding: &finding})
			}
		}

		emit(ctx, progress, ScanProgressEvent{Type: "category_completed", Category: category})
	}

	result.CompletedAt = time.Now().UTC()

	if result.Status == ScanRunning {
		result.Status = ScanCompleted
	}

	if result.Status == ScanCompleted {
		emit(ctx, progress, ScanProgressEvent{Type: "scan_completed"})
	} else {
		emit(ctx, progress, ScanProgressEvent{Type: "scan_failed", Error: result.ErrorMessage})
	}

	return result
}

// categories returns each rule's Category once, in first-seen order, so scan
// progress reports categories in a stable, deterministic sequence.
func (s *Scanner) categories() []string {
	seen := map[string]bool{}

	var order []string

	for _, r := range s.Rules {
		if !seen[r.Category] {
			seen[r.Category] = true

			order = append(order, r.Category)
		}
	}

	return order
}

// emit sends ev on ch, unless ctx is already done (client disconnected) or
// ch is nil (progress streaming disabled for this run).
func emit(ctx context.Context, ch chan<- ScanProgressEvent, ev ScanProgressEvent) {
	if ch == nil {
		return
	}

	select {
	case ch <- ev:
	case <-ctx.Done():
	}
}
